CREATE PROC usp_UpdateUser
@UserId INT, 
@FirstName VARCHAR(50),
@LastName VARCHAR(50),
@DateOfBirth DATETIME,
@EmailID VARCHAR(200),
@Gender INT,
@CompanyName VARCHAR(250),
@StreetAddress1 VARCHAR(500),
@StreetAddress2 VARCHAR(500),
@PostCode VARCHAR(50),
@City VARCHAR(50),
@StateId VARCHAR(50),
@Country VARCHAR(50),
@Phone VARCHAR(50),
@Fax VARCHAR(50),
@Password VARCHAR(50),
@IsTaxExempt BIT,
@IsAdmin BIT,
@AdminComment VARCHAR(50),
@Status INT,
@RegistrationDate DATETIME2,
@OrderUser INT,
@IsEmailValidated BIT,
@UpdateDate DATETIME2
AS
BEGIN
	UPDATE [User]
	SET FirstName = @FirstName,
	LastName = @LastName,
	DateOfBirth = @DateOfBirth,
	EmailID = @EmailID,
	Gender = @Gender,
	CompanyName = @CompanyName,
	StreetAddress1 = @StreetAddress1,
	StreetAddress2 = @StreetAddress2,
	PostCode = @PostCode,
	City = @City,
	StateId = @StateId,
	Country = @Country,
	Phone = @Phone,
	Fax = @Fax,
	Password = @Password,
	IsTaxExempt = @IsTaxExempt,
	IsAdmin = @IsAdmin,
	AdminComment = @AdminComment,
	Status = @Status,
	RegistrationDate = @RegistrationDate,
	OrderUser = @OrderUser,
	IsEmailValidated = @IsEmailValidated,
	UpdateDate = @UpdateDate
	WHERE UserId = @UserId
END
